apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: crochetcraft
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: crochetcraft
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: crochetcraft
type: Opaque
stringData:
  mysql-root-password: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-container
  labels:
    app: crochetcraft
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crochetcraft
      component: database
  template:
    metadata:
      labels:
        app: crochetcraft
        component: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: myapplication
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-container
  labels:
    app: crochetcraft
    component: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: crochetcraft
    component: database
  type: ClusterIP
